from . import product_template
from . import repair_order 
from . import repair_fee
from . import sale_order
from . import stock_picking
from . import repair_line
from . import repair_order_line_taller
from . import wizard
from . import wizard_taller
from . import repair_test
from . import stock_quant
from . import account_move
from . import repait_table1_taller
from . import repait_table2_taller
from . import wash_test